version: '3.4'

services:
  proxy:
    image: nginx:latest
    container_name: reverse_proxy_demo
    depends_on:
        - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT: "Development"
    image: towk/demoapp:latest
    ports:
      - 5032:80
